### ISSUE TITLE
Facing an Error Whilst Downloading

### ISSUE THREAD

**Issue by hasnainnaeem** [jim-schwoebel/download_audioset#3]
**Greetings,**
I'm facing an issue when I start downloading the data. This is the error I get:
```
hasnain@Hasnain:/mnt/d/Internship/Codes/New/download_audioset$ python3 as_download.py

  1,146,880 Bytes [85.11%] received. Rate: [  34 KB/s].  ETA: [6 secs]
no urls,566 Bytes [100.00%] received. Rate: [  32 KB/s].  ETA: [0 secs]
**Traceback (most recent call last):
  File "as_download.py", line 224, in <module>
    print('copying file to %s'%(newdir+snippedfile))
NameError: name 'snippedfile' is not defined**
```

I'm running it on Ubuntu subsystem on Windows 10. Do you think it is the cause of the error?
I made sure all the libraries were installed by running `setup.py` multiple times.

**Comment by narner** [comment]
I'm similarly seeing this on macOS

**Comment by piperwolters** [comment]
I am also facing this issue, any resolution?

**Comment by newbeepi** [comment]
use as_download_unbalanced.py
