### ISSUE TITLE
Downloading specific sounds

### ISSUE THREAD

**Issue by Sachindra2002** [jim-schwoebel/download_audioset#7]
Is there a way I could download specific sounds without the whole 32.5GB worth of sounds

**Comment by jim-schwoebel** [comment]
Hey Sachindra - I could totally do this at some point - I've been heads-down in work so haven't had a lot of time to work on this, but will try to post something in the coming weeks to help you all.

**Comment by ideacco** [comment]
I also need this feature, because I only need two or three classified resources

**Comment by Sachindra2002** [comment]
> I also need this feature, because I only need two or three classified resources

I would like this feature but as I was in a hurry I used the FSD50K dataset which is "an open dataset of human-labeled sound events containing 51,197 Freesound clips unequally distributed in 200 classes drawn from the AudioSet Ontology. FSD50K has been created at the Music Technology Group of Universitat Pompeu Fabra."

the whole dataset was around 17gb but it was split into 6 files and could be downloaded in less than one day without using a YouTube crawler which could take days.

FSD50K Dataset - https://zenodo.org/record/4060432#.YW69YxpByUk

**Comment by ideacco** [comment]
Ok, thank you very much for your reply, have a nice day

**Comment by jim-schwoebel** [comment]
I have open sourced the dataset on google drive here: https://drive.google.com/drive/folders/1OGSTJEPEYiWBsKTquPRth1H_ul6HKH9G?usp=sharing

Feel free to download there.
